<a href="https://colab.research.google.com/github/AlishaShaik1/ML-Algorithms-Practice/blob/main/My_ML_Practice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

KNN on iris data set

In [ ]:
from sklearn.datasets import load_iris
df=load_iris()
x=df.data
y=df.target
print(x)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
from sklearn.model_selection import train_test_split
xt,xte,yt,yte=train_test_split(x,y,test_size=0.3)
print(xt)
print(xte)
print(yt)
print(yte)

[['e' 'x' 's' ... 'e' 'k' 's']
 ['p' 'k' 's' ... 'e' 'w' 'v']
 ['e' 'x' 's' ... 'p' 'k' 'n']
 ...
 ['p' 'f' 'f' ... 'l' 'h' 'v']
 ['p' 'f' 'y' ... 'e' 'w' 'v']
 ['e' 'f' 'y' ... 'p' 'n' 'y']]
[['p' 'x' 'f' ... 'l' 'h' 'y']
 ['e' 'f' 'f' ... 'p' 'n' 'y']
 ['p' 'x' 'f' ... 'l' 'h' 'y']
 ...
 ['p' 'f' 'f' ... 'l' 'h' 'v']
 ['e' 'x' 's' ... 'e' 'k' 's']
 ['e' 'x' 's' ... 'p' 'k' 's']]
['g' 'l' 'm' ... 'p' 'p' 'd']
['g' 'd' 'd' ... 'p' 'g' 'g']


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
m=KNeighborsClassifier()
m.fit(xt,yt)
yp=m.predict(xte)
from sklearn.metrics import accuracy_score
print(accuracy_score(yte,yp))

0.9555555555555556


KNN on Msuhroom Data set

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

df = pd.read_csv('/content/mushrooms.csv')

x = df.iloc[:, 1:].values
y = df.iloc[:, 0].values
new_mushroom = [['x','s','n','t','p','f','c','n','k','e',
                 'e','s','s','w','w','p','w','o','p','k','s','u']]
le = LabelEncoder()
y = le.fit_transform(y)

ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
x = ohe.fit_transform(x)
new_mushroom_encoded = ohe.transform(new_mushroom)

In [ ]:
from sklearn.model_selection import train_test_split
xt,xte,yt,yte=train_test_split(x,y,test_size=0.3)
print(xt)
print(xte)
print(yt)
print(yte)

[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 1. 0. 0.]
 [1. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]
[0 1 0 ... 0 0 0]
[0 1 0 ... 0 0 0]


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
m=KNeighborsClassifier(n_neighbors=5)
m.fit(xt,yt)
yp=m.predict(xte)
from sklearn.metrics import accuracy_score
print(accuracy_score(yte,yp))
prediction = m.predict(new_mushroom_encoded)
result = le.inverse_transform(prediction)
print("Prediction:", result[0])


1.0
Prediction: p


KNN on Titanic Data set

In [16]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score


In [17]:
df = pd.read_csv('/content/Titanic-Dataset.csv')


In [29]:
X = df[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']]
y = df['Survived']

In [30]:
X.loc[:, 'Age'] = X['Age'].fillna(X['Age'].median())
X.loc[:, 'Embarked'] = X['Embarked'].fillna(X['Embarked'].mode()[0])

In [22]:
le_sex = LabelEncoder()
le_embarked = LabelEncoder()

X.loc[:, 'Sex'] = le_sex.fit_transform(X['Sex'])        # male/female → 0/1
X.loc[:, 'Embarked'] = le_embarked.fit_transform(X['Embarked'])

In [23]:
xt, xte, yt, yte = train_test_split(
    X, y, test_size=0.3, random_state=42
)


In [24]:
scaler = StandardScaler()
xt = scaler.fit_transform(xt)
xte = scaler.transform(xte)


In [25]:
model = KNeighborsClassifier(n_neighbors=5)
model.fit(xt, yt)


KNeighborsClassifier()

In [27]:
yp = model.predict(xte)
print("Test Accuracy:", accuracy_score(yte, yp))


Test Accuracy: 0.7873134328358209


Single Layer Nearul Network on Titanic Data set

In [45]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [47]:
df=pd.read_csv('/content/Titanic-Dataset.csv')

In [48]:
X=df[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']]
y=df['Survived']


In [49]:
X.loc[:, 'Age'] = X['Age'].fillna(X['Age'].median())
X.loc[:, 'Embarked'] = X['Embarked'].fillna(X['Embarked'].mode()[0])

In [31]:
le_sex=LabelEncoder()
le_emb=LabelEncoder()
X.loc[:, 'Sex']=le_sex.fit_transform(X['Sex'])
X.loc[:, 'Embarked'] = le_emb.fit_transform(X['Embarked'])

In [ ]:
xt,xte,yt,yte=train_test_split(X,y,test_size=0.3,random_state=42)

In [ ]:
scaler=StandardScaler()
xt=scaler.fit_transform(xt)
xte=scaler.transform(xte)

model=LogisticRegression()
model.fit(xt,yt)
yp=model.predict(xte)
print("Test Accuracy:",accuracy_score(yte,yp))

Test Accuracy: 0.8134328358208955


Multi Layer Neaural Network on Iris Data set

In [ ]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

In [ ]:
iris=load_iris()
X=iris.data
y=iris.target

xt,xte,yt,yte=train_test_split(X,y,test_size=00.3,random_state=42)

In [ ]:
scaler=StandardScaler()
xt=scaler.fit_transform(xt)
xte=scaler.transform(xte)


In [ ]:
model=MLPClassifier(hidden_layer_sizes=(10,),
activation='relu',
max_iter=1000,
random_state=42
)

In [ ]:
model.fit(xt,yt)
yp=model.predict(xte)
print("Accuracy:",accuracy_score(yte,yp))

Accuracy: 1.0


/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


In [ ]:
new_flower=[[5.1,3.5,1.4,0.2]]
new_flower_scaled=scaler.transform(new_flower)

prediction=model.predict(new_flower_scaled)
print("Predicted class:",iris.target_names[prediction[0]])

Predicted class: setosa


Heart Disease Prediction using Random Forest

In [38]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report


In [39]:
df = pd.read_csv('/content/Heart_Disease_Prediction.csv')

In [40]:
X=df.drop(columns=['Heart Disease'])
y=df['Heart Disease']

xt,xte,yt,yte=train_test_split(X,y,test_size=0.3,random_state=42)

In [41]:
model=RandomForestClassifier(n_estimators=100,random_state=42)

In [42]:
model.fit(xt, yt)
yp=model.predict(xte)
print("Accuracy:",accuracy_score(yte,yp))
print("\nClassification Report:\n",classification_report(yte,yp))


Accuracy: 0.7654320987654321

Classification Report:
               precision    recall  f1-score   support

     Absence       0.77      0.88      0.82        49
    Presence       0.76      0.59      0.67        32

    accuracy                           0.77        81
   macro avg       0.76      0.74      0.74        81
weighted avg       0.76      0.77      0.76        81



Pediction for new patient

In [44]:
new_patient = pd.DataFrame([[55,   # age
    1,    # sex (1=male)
    2,    # cp
    130,  # trestbps
    250,  # chol
    0,    # fbs
    1,    # restecg
    150,  # thalach
    0,    # exang
    1.5,  # oldpeak
    1,    # slope
    0,    # ca
    2     # thal
]], columns=['Age', 'Sex', 'Chest pain type', 'BP', 'Cholesterol', 'FBS over 120', 'EKG results', 'Max HR', 'Exercise angina', 'ST depression', 'Slope of ST', 'Number of vessels fluro', 'Thallium'])

prediction = model.predict(new_patient)
print("Heart Disease:", "YES" if prediction[0] == 1 else "NO")

Heart Disease: NO


LOGISTIC REGRESSION MODEL ON HEART DISEASE

In [5]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report


In [ ]:
df = pd.read_csv('/content/Heart_Disease_Prediction.csv')
X=df.drop(columns=['Heart Disease'])
y=df['Heart Disease']

xt,xte,yt,yte=train_test_split(X,y,test_size=0.3,random_state=42)

In [ ]:
scaler = StandardScaler()
xt = scaler.fit_transform(xt)
xte = scaler.transform(xte)


In [ ]:
model = LogisticRegression(
    max_iter=5000,        # important for large feature set
    solver='saga',        # best for many features
    penalty='l2',         # regularization
    n_jobs=-1
)


In [ ]:
model.fit(xt, yt)
yp = model.predict(xte)

print("Accuracy:", accuracy_score(yte, yp))
print("\nClassification Report:\n", classification_report(yte, yp))


Accuracy: 0.8271604938271605

Classification Report:
               precision    recall  f1-score   support

     Absence       0.81      0.94      0.87        49
    Presence       0.88      0.66      0.75        32

    accuracy                           0.83        81
   macro avg       0.84      0.80      0.81        81
weighted avg       0.83      0.83      0.82        81



Multi-Layer Neural Network On Heart Disease

In [4]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report


In [ ]:
xt, xte, yt, yte = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [ ]:
scaler = StandardScaler()
xt = scaler.fit_transform(xt)
xte = scaler.transform(xte)


In [ ]:
mlp = MLPClassifier(
    hidden_layer_sizes=(128, 64),
    activation='relu',
    solver='adam',
    alpha=0.001,
    batch_size=32,
    learning_rate='adaptive',
    max_iter=1000,
    random_state=42,
    early_stopping=True
)


In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_train_encoded = le.fit_transform(yt)
y_test_encoded = le.transform(yte)

mlp.fit(xt, y_train_encoded)
yp = mlp.predict(xte)

print("MLP Accuracy:", accuracy_score(y_test_encoded, yp))
print("\nClassification Report:\n", classification_report(y_test_encoded, yp))

MLP Accuracy: 0.8271604938271605

Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.94      0.87        49
           1       0.88      0.66      0.75        32

    accuracy                           0.83        81
   macro avg       0.84      0.80      0.81        81
weighted avg       0.83      0.83      0.82        81



In [12]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(
    RandomForestClassifier(random_state=42),
    X, y,
    cv=5,
    scoring='accuracy'
)

print("CV Accuracy:", scores.mean())


CV Accuracy: 0.8185185185185183
